Repository flow-typed/flow-typed, pull requests merged in 2018-09, with the labels that each got.

#2683 Fix custom dispatch in react redux
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-v0.67.x/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-v0.67.x/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-v0.67.x/test_connect.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-v0.67.x/test_connectAdvanced.js
  definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/test_connect.js
  definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/test_connectAdvanced.js
Labels: enhancement, libdef, needs-updates

#2691 axios split progress config option into onUploadProgress and onDownloadProgress in v0.14
  definitions/npm/axios_v0.15.x/flow_v0.25.x-v0.74.x/axios_v0.15.x.js
  definitions/npm/axios_v0.16.x/flow_v0.25.x-v0.74.x/axios_v0.16.x.js
  definitions/npm/axios_v0.16.x/flow_v0.75.x-/axios_v0.16.x.js
  definitions/npm/axios_v0.17.x/flow_v0.25.x-v0.74.x/axios_v0.17.x.js
  definitions/npm/axios_v0.17.x/flow_v0.75.x-/axios_v0.17.x.js
  definitions/npm/axios_v0.18.x/flow_v0.25.x-v0.74.x/axios_v0.18.x.js
  definitions/npm/axios_v0.18.x/flow_v0.75.x-/axios_v0.18.x.js
Labels: enhancement, libdef, needs-updates

#2542 Added pipeK definition for Ramda
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_functions.js
Labels: changes-requested, enhancement, libdef

#2749 Refactor validation error handling
  cli/flow-typed/npm/jest_v23.x.x.js
  cli/src/commands/__tests__/install-test.js
  cli/src/commands/__tests__/search-test.js
  cli/src/commands/install.js
  cli/src/commands/runTests.js
  cli/src/commands/validateDefs.js
  cli/src/lib/ValidationError.js
  cli/src/lib/__tests__/flowVersion-test.js
  cli/src/lib/__tests__/libDefs-test.js
  cli/src/lib/flowVersion.js
  cli/src/lib/libDefs.js
  cli/src/lib/npm/__tests__/npmLibDefs-test.js
  cli/src/lib/npm/npmLibDefs.js
  cli/src/lib/validationErrors.js
Labels: cli
