Repository flow-typed/flow-typed, pull requests merged in 2018-11, with the labels that each got.

#2910 Add flow-typed definitions for Webpack4
  definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js
  definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js
Labels: libdef, new, work-in-progress

#2873 Add libdef for http-link-header
  definitions/npm/http-link-header_v1.x.x/flow_v0.25.x-/http-link-header_v1.x.x.js
  definitions/npm/http-link-header_v1.x.x/test_http-link-header_v1.x.x.js
Labels: changes-requested, libdef, new

#2768 Redux saga v1
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/redux-saga_v1.x.x.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_CANCEL.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_END.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_MulticastChannel.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_SAGA_LOCATION.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_actionChannel.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_all.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_apply.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_buffers.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_async.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_context_async.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_context_generator.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_context_normal.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_generator.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_call_normal.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_cancel.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_cancelled.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_channel.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_cps.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_debounce.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_default.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_delay.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_detach.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_eventChannel.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_flush.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_fork.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_getContext.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_high-level-api-takes.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_isEnd.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_join.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_put.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_putResolve.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_race.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_retry.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_runSaga.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_select.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_setContext.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_spawn.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_take.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_takeMaybe.js
  definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_throttle.js
Labels: libdef, new

#2953 Add zipkin defs
  definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_model.js
  definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_option.js
  definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_recorder.js
  definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_tracer.js
  definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/zipkin_v0.14.x.js
Labels: changes-requested, libdef, new

#2941 Accepting a type T as options to support custom rendered options
  definitions/npm/react-select_v1.x.x/flow_v0.53.x-/react-select_v1.x.x.js
  definitions/npm/react-select_v1.x.x/flow_v0.53.x-/test_react-select_v1.x.x.js
Labels: question
