Repository flow-typed/flow-typed, pull requests merged in 2018-02, with the labels that each got.

#1835 flowtype/flow-typed#1760 Add root directory option to CLI
  cli/src/commands/__tests__/install-test.js
  cli/src/commands/create-stub.js
  cli/src/commands/install.js
Labels: cli-bug, enhancement

#1844 Add nano-md5_v1.x.x
  definitions/npm/nano-md5_v1.x.x/flow_v0.65.x-/nano-md5_v1.x.x.js
  definitions/npm/nano-md5_v1.x.x/test_nano-md5_v1.x.x.js
Labels: needs-updates

#1756 Ramda#pathOr accepts numbers for path.
  definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/test_ramda_v0.x.x_object.js
Labels: needs-updates

#1854 Fix failing regression spec
  cli/src/commands/__tests__/runTests-test.js
Labels: cli-bug

#1851 libdef lodash: Fix flow, flowRight, pipe, and Compose
  definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/lodash_v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
Labels: needs-updates

#1864 Add babel-core peer dependency, fix Jest breaking
  cli/package.json
  cli/yarn.lock
Labels: cli-bug

#1853 History v4: add initial definition
  definitions/npm/history_v4.x.x/flow_v0.25.x-/history_v4.x.x.js
  definitions/npm/history_v4.x.x/flow_v0.25.x-/test_history_v4.x.x.js
Labels: on-hold

#1866 jsonwebtoken definition
  definitions/npm/jsonwebtoken_v8.1.x/flow_v0.56.x-/jsonwebtoken_v8.1.x.js
  definitions/npm/jsonwebtoken_v8.1.x/test_jsonwebtoken_v8.1.x.js
Labels: enhancement

#1867 add react-color
  definitions/npm/react-color_v2.x.x/flow_v0.56.x-/react-color_v2.x.x.js
  definitions/npm/react-color_v2.x.x/flow_v0.56.x-/test_react-color_v2.x.x.js
Labels: needs-updates

#1858 Add Jest support for using class and function as test name in describe() and test()
  definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Labels: on-hold

#1570 Added typedef for xml-escape
  definitions/npm/xml-escape_v1.x.x/flow_v0.25.x-/xml-escape_v1.x.x.js
  definitions/npm/xml-escape_v1.x.x/test_xml-escape_v1.x.x.js
Labels: needs-updates

#1702 Add escape-html_v1.x.x
  definitions/npm/escape-html_v1.x.x/flow_v0.25.x-/escape-html_v1.x.x.js
  definitions/npm/escape-html_v1.x.x/test_escape-html_v1.x.x.js
Labels: needs-updates, new-libdef

#1872 [redux-form] Update redux-form for flow 53+
  definitions/npm/redux-form_v5.x.x/flow_v0.25.x-v0.52.x/test_redux-form_v5.x.x.js
  definitions/npm/redux-form_v5.x.x/flow_v0.53.x-/redux-form_v5.x.x.js
  definitions/npm/redux-form_v5.x.x/flow_v0.53.x-/test_redux-form_v5.x.x.js
Labels: needs-updates

#1811 Improve hoist non react statics defs
  definitions/npm/hoist-non-react-statics_v2.4.x/flow_v0.54.1-/hoist-non-react-statics_v2.4.x.js
  definitions/npm/hoist-non-react-statics_v2.x.x/flow_v0.54.1-/hoist-non-react-statics_v2.x.x.js
  definitions/npm/hoist-non-react-statics_v2.x.x/test_hoist-non-react-statics_v2.x.x.js
Labels: question

#1884 Redis: update callback type annotations
  definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
  definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Labels: needs-updates

#1897 Fix mixed/any problems in socket.io-client
  definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
  definitions/npm/socket.io-client_v2.x.x/test_socket.io-client_v2.x.x.js
Labels: question
