Repository flow-typed/flow-typed, pull requests merged in 2018-06, with the labels that each got.

#2292 Add opentok 2.6.2 defs
  definitions/npm/opentok_v2.6.x/flow_v0.61.x-/opentok_v2.6.x.js
  definitions/npm/opentok_v2.6.x/flow_v0.61.x-/test_opentok.js
Labels: changes-requested, libdef, new

#2310 Create cors_v2.x.x.js
  definitions/npm/cors_v2.x.x/flow_v0.53.x/cors_v2.x.x.js
  definitions/npm/cors_v2.x.x/flow_v0.53.x/test_cors.js
Labels: changes-requested, libdef, new

#2318 lodash: allow get to receive $ReadOnlyArray
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
Labels: changes-requested, enhancement, libdef

#2313 lodash: isString should accept any like other isX methods
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
Labels: enhancement, libdef, on-hold

#2280 Update react-navigation_v1.x.x from the lastest of react-navigation repo
  definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
Labels: needs-updates

#2326 react-modal: able to use promise for onAfterOpen
  definitions/npm/react-modal_v3.1.x/flow_v0.54.1-/react-modal_v3.1.x.js
  definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js
Labels: enhancement, libdef, needs-updates

#2250 Add react image crop 3 definition
  definitions/npm/react-image-crop_v3.x.x/flow_v0.32.x-/react-image-crop_v3.x.x.js
  definitions/npm/react-image-crop_v3.x.x/test_react-image-crop_v3.x.x.js
  definitions/npm/react-image-crop_v4.x.x/flow_v0.32.x-/react-image-crop_v4.x.x.js
  definitions/npm/react-image-crop_v4.x.x/test_react-image-crop_v4.x.x.js
Labels: enhancement, libdef

#2124 lodash and lodash/fp: get/getOr accept nil collections
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
Labels: libdef, needs-updates

#2342 relax react-router-dom Link constraints
  definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
  definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/test_react-router-dom.js
Labels: enhancement, libdef

#2344 Add redux v4 libdef.
  definitions/npm/redux_v4.x.x/flow_v0.55.x-/redux_v4.x.x.js
  definitions/npm/redux_v4.x.x/flow_v0.55.x-/test_applyMiddleware.js
  definitions/npm/redux_v4.x.x/flow_v0.55.x-/test_combineReducers.js
  definitions/npm/redux_v4.x.x/flow_v0.55.x-/test_createStore.js
  definitions/npm/redux_v4.x.x/flow_v0.55.x-/test_custom_dispatch.js
Labels: libdef, new

#2355 Handle uninstalling of scoped packages
  cli/src/commands/install.js
  cli/src/lib/npm/__tests__/npmLibDefs-test.js
  cli/src/lib/npm/npmLibDefs.js
Labels: cli, enhancement

#2385 ESLint fixes to install file
  cli/src/commands/install.js
  cli/src/lib/npm/__tests__/npmLibDefs-test.js
Labels: cli, enhancement

#2423 Ignore 0.63 when running travis builds
  cli/src/commands/runTests.js
Labels: bug, cli

#2426 Add definition for @reach/router
  definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-/router_v1.1.x.js
  definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-/test_router_v1.1.x.js
Labels: changes-requested, libdef, new

#2416 Update styled-components for flow v0.75.0
  definitions/npm/styled-components_v2.x.x/flow_v0.53.x-v0.74.x/styled-components_v2.x.x.js
  definitions/npm/styled-components_v2.x.x/flow_v0.53.x-v0.74.x/test_styled-components_native_v2.x.x.js
  definitions/npm/styled-components_v2.x.x/flow_v0.53.x-v0.74.x/test_styled-components_v2.x.x.js
  definitions/npm/styled-components_v2.x.x/flow_v0.75.x-/styled-components_v2.x.x.js
  definitions/npm/styled-components_v2.x.x/flow_v0.75.x-/test_styled-components_native_v2.x.x.js
  definitions/npm/styled-components_v2.x.x/flow_v0.75.x-/test_styled-components_v2.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.57.x-v0.74.x/styled-components_v3.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.57.x-v0.74.x/test_styled-components_native_v3.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.57.x-v0.74.x/test_styled-components_v3.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/styled-components_v3.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/test_styled-components_native_v3.x.x.js
  definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/test_styled-components_v3.x.x.js
Labels: changes-requested, enhancement, libdef

#2248 Add generic Function type to Jasmine Spy
  definitions/npm/jasmine_v2.4.x/flow_v0.25.x-/jasmine_v2.4.x.js
Labels: changes-requested, enhancement, libdef

#2381 Allow Parse.ACL() constructor without arguments
  definitions/npm/parse_v1.9.x/flow_v0.30.x-/parse_v1.9.x.js
Labels: changes-requested, enhancement, libdef

#2404 Update styled-components-v3.x.x definitions
  definitions/npm/styled-components_v3.x.x/flow_v0.57.x-v0.74.x/styled-components_v3.x.x.js
Labels: enhancement, libdef, needs-updates
