Repository flow-typed/flow-typed, pull requests merged in 2018-05, with the labels that each got.

#2082 [algoliasearch] Fix async import() case
  definitions/__util__/tdd_framework.js
  definitions/npm/algoliasearch_v3.x.x/flow_v0.56.x-/algoliasearch_v3.x.x.js
  definitions/npm/algoliasearch_v3.x.x/test_algoliasearch-v3.x.x.js
Labels: enhancement, libdef

#2063 Add libdef for react-splitter-layout
  definitions/npm/react-splitter-layout_v3.x.x/flow_v0.53.x-/react-splitter-layout_v3.x.x.js
  definitions/npm/react-splitter-layout_v3.x.x/flow_v0.53.x-/test_splitter-layout.js
Labels: libdef, new

#2069 Export ApolloConsumer component with react-apollo
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Labels: enhancement, libdef

#2098 Update sequelize transaction auto callback method signature
  definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
  definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
Labels: enhancement, libdef, on-hold

#2032 Some additions to mongoose@4.0.0
  definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js
Labels: changes-requested, enhancement, libdef

#2161 Jest 22.X.X - Chore: Update spyOn type to reflect third optional accessType argument
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Labels: incomplete, libdef

#2158 Support to use string template for chalk
  definitions/npm/chalk_v2.x.x/flow_v0.25.x-/chalk_v2.x.x.js
  definitions/npm/chalk_v2.x.x/test_chalk_v2.x.x.js
Labels: changes-requested, enhancement, libdef

#2149 fix react-dnd connector type to mesh well with recompose
  definitions/npm/react-dnd_v2.x.x/flow_v0.53.x-/react-dnd_v2.x.x.js
Labels: enhancement, libdef

#2154 Clarify usage of ES6 syntax for creating modules.
  CONTRIBUTING.md
Labels: changes-requested, documentation

#2169 Make throttle-debounce function accept arguments
  definitions/npm/throttle-debounce_v1.x.x/flow_v0.25.x-/throttle-debounce_v1.x.x.js
Labels: changes-requested, libdef

#2159 add directory-tree
  definitions/npm/directory-tree_v2.x.x/flow_v0.71.x-/directory-tree_v2.x.x.js
  definitions/npm/directory-tree_v2.x.x/test_directory-tree_v2.x.x.js
Labels: libdef, new

#2167 add Subscription component to react-apollo defs
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Labels: changes-requested, libdef

#2140 update to latest from react-navigation/1.x
  definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
Labels: libdef, on-hold

#2168 fix(sequelize): fix invalid errors from BelongsToMany association definitions
  definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
Labels: enhancement, libdef

#2179 Add stringify-object declaration
  definitions/npm/stringify-object_v3.x.x/flow_v0.50.x-/stringify-object_v3.x.x.js
  definitions/npm/stringify-object_v3.x.x/test_stringify-object_3.x.x.js
Labels: changes-requested, libdef

#2171 Fix problems with Formik types
  definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
  definitions/npm/formik_v0.11.x/test_formik.js
Labels: enhancement, libdef

#2184 [rethinkdb] Start libdef on rethink db
  definitions/npm/rethinkdb_v2.x.x/flow_v0.68.x-/rethinkdb_v2.x.x.js
  definitions/npm/rethinkdb_v2.x.x/test_rethinkdb_v2.x.x.js
Labels: libdef, new, work-in-progress

#2170 Add libdef knex 0.14
  definitions/npm/knex_v0.14.x/flow_v0.38.x-/knex_v0.14.x.js
  definitions/npm/knex_v0.14.x/test_knex-v0.14.js
Labels: libdef, new

#2185 RxJS: Allow filtering maybe types with Boolean
  definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
  definitions/npm/rxjs_v5.0.x/test_rxjs.js
Labels: changes-requested, enhancement, libdef

#2198 feat: add mitt v1 definitions
  definitions/npm/mitt_v1.x.x/flow_v0.28.x-/mitt_v1.x.x.js
  definitions/npm/mitt_v1.x.x/test_mitt_v1.x.x.js
Labels: changes-requested, libdef, new

#2174 Export koa-bodyparser as a CommonJS module
  definitions/npm/koa-bodyparser_v4.x.x/flow_v0.56.x-/koa-bodyparser_v4.x.x.js
  definitions/npm/koa-bodyparser_v4.x.x/flow_v0.56.x-/test_koa-bodyparser_v4.x.x.js
Labels: libdef, on-hold

#2204 Add new libdefs for react-testing-library@3
  definitions/npm/react-testing-library_v3.x.x/flow_v0.60.0-/react-testing-library_v3.x.x.js
  definitions/npm/react-testing-library_v3.x.x/flow_v0.60.0-/test_react-testing-library_v3.x.x.js
Labels: libdef, new

#2236 [react-onclickoutside] Add missing IGNORE_CLASS_NAME export
  definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/react-onclickoutside_v6.x.x.js
  definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/test_react-onclickoutside_v6.x.x.js
Labels: enhancement, libdef

#2234 [knex] Add some missing methods to knex definitions
  definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js
  definitions/npm/knex_v0.13.x/test_knex-v0.13.js
  definitions/npm/knex_v0.14.x/flow_v0.38.x-/knex_v0.14.x.js
  definitions/npm/knex_v0.14.x/test_knex-v0.14.js
Labels: changes-requested, enhancement, libdef

#2225 [react-transition-group] Replace an interface with an object type
  definitions/npm/react-transition-group_v2.x.x/flow_v0.60.x-/react-transition-group_v2.x.x.js
  definitions/npm/react-transition-group_v2.x.x/test_react-transition-group.js
Labels: enhancement, libdef, work-in-progress

#2247 Fix ramda startsWith and endsWith
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
Labels: bug, enhancement, libdef

#2223 [react-redux] Add ability to use MDP Object with mergeProps
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.62.x/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.62.x/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.62.x/test_connect.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_connect.js
Labels: enhancement, libdef

#2219 [amqplib] Introduce libdef for amqplib@0.9.1
  definitions/npm/amqplib_v0.5.x/flow_v0.60.1-/amqplib_v0.5.x.js
  definitions/npm/amqplib_v0.5.x/flow_v0.60.1-/test_amqplib_v0.5.x.js
Labels: changes-requested, libdef, new
