Repository flow-typed/flow-typed, pull requests merged in 2018-04, with the labels that each got.

#1707 add select() and put.resolve() to redux-saga definitions
  definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js
  definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/test_redux-saga_0.16.x.js
Labels: libdef, on-hold

#2022 Fluture: Removed global and renamed export to be less confusing
  definitions/npm/fluture_v6.x.x/flow_v0.34.x-/fluture_v6.x.x.js
Labels: libdef

#2013 Adding libdef for Winston Logging Package
  definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
  definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js
Labels: enhancement, libdef

#2011 Added libdef for @nx-js/observer-util
  definitions/npm/@nx-js/observer-util_v4.x.x/flow_v0.25.x-/observer-util_v4.x.x.js
  definitions/npm/@nx-js/observer-util_v4.x.x/test_observer-util_v4.x.x.js
Labels: enhancement, libdef

#1821 Update next-routes_v1.x.x.js
  definitions/npm/next-routes_v1.x.x/flow_v0.47.x-/next-routes_v1.x.x.js
Labels: changes-requested, libdef

#1925 Update react-navigation libdef
  definitions/npm/react-navigation_v1.x.x/CONTRIBUTING.md
  definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
Labels: libdef, needs-updates

#1992 Cleanup runTests a bit
  cli/src/commands/runTests.js
Labels: cli, on-hold

#1998 Add mockName type to jest mocked functions
  cli/flow-typed/npm/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Labels: changes-requested, libdef

#2019 Support stateless in react css modules
  definitions/npm/react-css-modules_v3.x.x/flow_v0.53.x-/react-css-modules_v3.x.x.js
  definitions/npm/react-css-modules_v3.x.x/flow_v0.53.x-/test_react-css-modules-v3.js
Labels: changes-requested, libdef

#2029 update promise-retry
  definitions/npm/promise-retry_v1.1.x/flow_v0.45.x-/promise-retry_v1.1.x.js
Labels: changes-requested, libdef

#2043 Jasmine: Add `.and` for spies, `pending`, `DEFAULT_TIMEOUT_INTERVAL`
  definitions/npm/jasmine_v2.4.x/flow_v0.25.x-/jasmine_v2.4.x.js
  definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x.js
  definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_pending.js
  definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_spies.js
Labels: enhancement, libdef

#2049 update puppeteer typedef and tests
  definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/puppeteer_v1.2.x.js
  definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_connect.js
  definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_defaultArgs.js
  definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_executablePath.js
  definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_launch.js
Labels: changes-requested, enhancement, libdef

#2016 Set cache directory with arguments of install and update commands
  cli/src/commands/install.js
  cli/src/commands/update-cache.js
Labels: changes-requested, cli, enhancement

#2042 Port more tests for react-apollo definitions
  definitions/npm/react-apollo_v2.x.x/flow_v0.50.x-/test_react-apollo_v2.x.x.js
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
Labels: enhancement, libdef

#2055 Add libdef for global
  definitions/npm/global_v4.x.x/flow_v0.52.x-/global_v4.x.x.js
  definitions/npm/global_v4.x.x/test_global.js
Labels: changes-requested, libdef, new

#2062 React testing library libdefs
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
  definitions/npm/react-testing-library_v2.x.x/flow_v0.58.0-/react-testing-library_v2.x.x.js
  definitions/npm/react-testing-library_v2.x.x/flow_v0.58.0-/test_react-testing-library_v2.x.x.js
Labels: libdef, new

#2018 [react-redux] Add default export
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
Labels: changes-requested, libdef

#2058 react-i18next libdef update
  definitions/npm/react-i18next_v7.x.x/flow_v0.53.x-0.61.x/react-i18next_v7.x.x.js
  definitions/npm/react-i18next_v7.x.x/flow_v0.53.x-0.61.x/test_react-i18next_v7.x.x.js
  definitions/npm/react-i18next_v7.x.x/flow_v0.62.x-/react-i18next_v7.x.x.js
  definitions/npm/react-i18next_v7.x.x/flow_v0.62.x-/test_react-i18next_v7.x.x.js
Labels: enhancement, libdef

#2057 [react-redux] Parameterize MapStateToProps on Redux state
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
Labels: libdef, needs-updates

#2030 Add query-string_v6.x.x definitions
  definitions/npm/query-string_v5.1.x/flow_v0.32.x-/query-string_v5.1.x.js
  definitions/npm/query-string_v5.1.x/flow_v0.32.x-/test_query-string_v5.1.x.js
  definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js
  definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js
Labels: libdef, new

#2066 [react-testing-library] version 2.1 definitions
  definitions/npm/react-testing-library_v2.0.x/flow_v0.58.0-/react-testing-library_v2.0.x.js
  definitions/npm/react-testing-library_v2.0.x/flow_v0.58.0-/test_react-testing-library_v2.0.x.js
  definitions/npm/react-testing-library_v2.1.x/flow_v0.58.0-/react-testing-library_v2.1.x.js
  definitions/npm/react-testing-library_v2.1.x/flow_v0.58.0-/test_react-testing-library_v2.1.x.js
Labels: enhancement, libdef, on-hold

#2070 [pretty-error] Improve return values
  definitions/npm/pretty-error_v2.x.x/flow_v0.25.x-/pretty-error_v2.x.x.js
  definitions/npm/pretty-error_v2.x.x/test_pretty-error-v2.js
Labels: enhancement, libdef

#2036 feat(jsonwebtoken): improve jsonwebtoken types
  definitions/npm/jsonwebtoken_v8.2.x/flow_v0.56.x-/jsonwebtoken_v8.2.x.js
  definitions/npm/jsonwebtoken_v8.2.x/test_jsonwebtoken_v8.2.x.js
Labels: changes-requested, libdef, new

#2064 Added definition for pg@7.x.x
  definitions/npm/pg_v7.x.x/flow_v0.28.x-/pg_v7.x.x.js
  definitions/npm/pg_v7.x.x/test_pg_v7.x.x.js
Labels: libdef, new

#2045 Update redux-actions to match updated redux definitions
  definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js
  definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_handleActions.js
Labels: enhancement, libdef

#1991 feat(formik): improve formik types
  definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
  definitions/npm/formik_v0.11.x/test_formik.js
Labels: changes-requested, libdef, question

#2092 Add libdef for url-parse
  definitions/npm/url-parse_v1.3.x/flow_v0.59.x-/url-parse_v1.3.x.js
  definitions/npm/url-parse_v1.3.x/test_url-parse.js
Labels: changes-requested, libdef, new

#1959 Do not require component usage to type check in react-redux
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/test_connect.js
Labels: libdef, work-in-progress

#2096 Use proper types for addSnapshotSerializer
  cli/flow-typed/npm/jest_v22.x.x.js
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js
  definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
  definitions/npm/jest_v21.x.x/flow_v0.39.x-/test_jest-v21.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Labels: enhancement, libdef

#2101 lodash/fp: Fix compact, unset, dissoc, dissocPath
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
Labels: changes-requested, enhancement, libdef

#2103 Fix typo in InjectIntlOtions type
  definitions/npm/react-intl_v2.x.x/flow_v0.57.x-/react-intl_v2.x.x.js
Labels: enhancement, libdef

#2107 Replace deprecated github@0.2.4 with Octokit
  cli/package.json
  cli/src/commands/runTests.js
  cli/src/lib/github.js
  cli/yarn.lock
Labels: cli, enhancement

#2027 Add new stub generation with guessed properties
  cli/src/commands/create-stub.js
  cli/src/lib/stubUtils.js
Labels: cli, enhancement

#2059 First draft of RxJS 6 support
  definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
  definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/test_rxjs.js
Labels: libdef, new

#2133 redux-exr
  definitions/npm/redux-exr_v0.4.x/flow_v0.65.x-/redux-exr_v0.4.x.js
  definitions/npm/redux-exr_v0.4.x/flow_v0.65.x-/test_exCombineReducers.js
  definitions/npm/redux-exr_v0.4.x/flow_v0.65.x-/test_makeExReducer.js
  definitions/npm/redux-exr_v0.4.x/flow_v0.65.x-/test_makePlainReducer.js
Labels: libdef, new

#2141 Update type to variant in <Typography>
  definitions/npm/material-ui_v1.x.x/flow_v0.58.x-/material-ui_v1.x.x.js
Labels: libdef, on-hold
