Repository flow-typed/flow-typed, pull requests merged in 2018-08, with the labels that each got.

#2538 directory-tree: change Array to ReadOnlyArray
  definitions/npm/directory-tree_v2.x.x/flow_v0.71.x-/directory-tree_v2.x.x.js
  definitions/npm/directory-tree_v2.x.x/test_directory-tree_v2.x.x.js
Labels: enhancement, libdef

#2578 Use /bin/sh instead of /bin/bash for better portability
  build_and_test_cli.sh
  quick_run_def_tests.sh
  travis.sh
Labels: cli, enhancement, question

#2603 Make CookiesSetOptions with defaults optional
  definitions/npm/koa_v2.0.x/flow_v0.47.x-/koa_v2.0.x.js
  definitions/npm/koa_v2.x.x/flow_v0.47.x-/koa_v2.x.x.js
Labels: bug, enhancement, libdef

#2567 [material-ui] Improve CircularProgress definition
  definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
  definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js
Labels: enhancement, libdef, needs-updates

#2582 [js-cookie]: change getJSON type to Object
  definitions/npm/js-cookie_v2.x.x/flow_v0.38.x-/js-cookie_v2.x.x.js
  definitions/npm/js-cookie_v2.x.x/flow_v0.38.x-/test_js-cookie-v2.x.x.js
Labels: enhancement, libdef, needs-updates

#2610 Skip 0.70 to address segfaults on travis
  cli/src/commands/runTests.js
Labels: bug, cli

#2572 [Winston] Add extra parameters to log methods
  definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
Labels: enhancement, libdef, needs-updates

#2530 fix type coverage on react-redux's connect
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js
Labels: bug, libdef

#2209 Add cron libdef
  definitions/npm/cron_v1.x.x/flow_v0.57.3-/cron_v1.x.x.js
  definitions/npm/cron_v1.x.x/test_cron_v1.x.x.js
Labels: libdef, needs-updates, new

#2421 Upate Knex def for 0.75
  definitions/npm/knex_v0.12.x/flow_v0.38.x-v0.74.x/knex_v0.12.x.js
  definitions/npm/knex_v0.13.x/flow_v0.38.x-v0.74.x/knex_v0.13.x.js
  definitions/npm/knex_v0.14.x/flow_v0.38.x-v0.74.x/knex_v0.14.x.js
  definitions/npm/knex_v0.14.x/flow_v0.38.x-v0.74.x/test_knex-v0.14.js
  definitions/npm/knex_v0.14.x/flow_v0.75.x-/knex_v0.14.x.js
  definitions/npm/knex_v0.14.x/flow_v0.75.x-/test_knex-v0.14.js
  definitions/npm/knex_v0.15.x/flow_v0.38.x-v0.74.x/knex_v0.15.x.js
  definitions/npm/knex_v0.15.x/flow_v0.38.x-v0.74.x/test_knex_v0.15.x.js
  definitions/npm/knex_v0.15.x/flow_v0.75.x-/knex_v0.15.x.js
  definitions/npm/knex_v0.15.x/flow_v0.75.x-/test_knex_v0.15.x.js
Labels: changes-requested, libdef, new

#2516 Add definitions for simple-query-string
  definitions/npm/simple-query-string_v1.x.x/flow_v0.25.x-/simple-query-string_v1.x.x.js
  definitions/npm/simple-query-string_v1.x.x/flow_v0.25.x-/test_simple-query-string_v1.x.x.js
Labels: changes-requested, libdef, new

#2632 Properly deal with injected props in withStyles function of material-ui
  definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
  definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js
Labels: changes-requested, enhancement, libdef

#2587 fix(react-apollo): fix refetchQueries types
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
Labels: enhancement, libdef, needs-updates

#2670 Update FormattedMessage in react-intl_v2.x.x.js
  definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/react-intl_v2.x.x.js
  definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/test_react-intl_v2.x.x.js
Labels: changes-requested, enhancement, libdef

#2666 Add `Card` & `Step` component definitions to `antd`
  definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
  definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js
Labels: enhancement, libdef
