Repository flow-typed/flow-typed, pull requests merged in 2018-07, with the labels that each got.

#2444 lodash: when using _.get, keys can be numbers (for the array case)
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
Labels: enhancement, libdef, needs-updates

#2450 [ramda] add types for chain function
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
Labels: changes-requested, enhancement, libdef

#2408 Update express_v4.x.x defs for compatibility with flow_v0.75.0
  definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js
  definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
Labels: changes-requested, enhancement, libdef

#2452 Formik improvements
  definitions/npm/formik_v0.11.x/flow_v0.59.x-/formik_v0.11.x.js
  definitions/npm/formik_v0.11.x/test_formik.js
Labels: enhancement, libdef

#2455 Add libdef for metalsmith 2.x.x
  definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/metalsmith_v2.x.x.js
  definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/test_metalsmith.js
Labels: changes-requested, libdef, new

#2443 [react-redux] Support static properties hoisting in connect
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_connect.js
Labels: enhancement, libdef

#2485 Temporarily disable stub guessing
  CHANGELOG.md
  cli/package.json
  cli/src/lib/stubUtils.js
Labels: bug, cli

#2475 add typings for empty / isEmpty / notEmpty / isNotEmpty in chaijs assert
  definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js
Labels: enhancement, libdef

#2489 metalsmith_v2.x.x: Fix File type to be less strict
  definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/metalsmith_v2.x.x.js
Labels: bug, changes-requested, libdef

#2430 Add storybook-addon-a11y definitions
  definitions/npm/@storybook/addon-a11y_v3.x.x/flow_v0.25.x-0.52.x/addon-a11y_v3.x.x.js
  definitions/npm/@storybook/addon-a11y_v3.x.x/flow_v0.53.x-/addon-a11y_v3.x.x.js
  definitions/npm/@storybook/addon-a11y_v3.x.x/test_addon-a11y_v3.x.x.js
Labels: changes-requested, libdef, new

#2451 redux-saga - declare takeLeading
  definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js
Labels: enhancement, libdef, needs-updates

#2498 react-apollo: Fix $call deprecated error on flow 0.75-
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Labels: enhancement, libdef

#2410 Added missing type for Glyphicon
  definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js
  definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/test_react-bootstrap_v0.32.x.js
Labels: changes-requested, enhancement, libdef

#2147 Delete second parameter in removeAllListeners in socket.io-client
  definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
  definitions/npm/socket.io-client_v2.x.x/test_socket.io-client_v2.x.x.js
Labels: changes-requested, libdef

#2503 Improve scripts for faster testing feedback loop; improve docs.
  CONTRIBUTING.md
  build_and_test_cli.cmd
  build_and_test_cli.sh
  quick_run_def_tests.cmd
  quick_run_def_tests.sh
Labels: documentation

#2499 fuzzaldrin-plus v0.6.0
  definitions/npm/fuzzaldrin-plus_v0.6.0/CONTRIBUTING.md
  definitions/npm/fuzzaldrin-plus_v0.6.0/flow_v0.25.x-/fuzzaldrin-plus_v0.6.0.js
  definitions/npm/fuzzaldrin-plus_v0.6.0/flow_v0.25.x-/test_fuzzaldrin-plus.js
Labels: libdef, new, work-in-progress

#2523 Added Fluture v8 definitions
  definitions/npm/fluture_v8.x.x/flow_v0.34.x-/fluture_v8.x.x.js
  definitions/npm/fluture_v8.x.x/flow_v0.34.x-/test_fluture_v8.x.x.js
Labels: changes-requested, libdef, new

#2520 add the ability to refine types from Ramda's filter
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
Labels: changes-requested, enhancement, libdef

#2513 Add libdef NewRelic 4.x.x
  definitions/npm/newrelic_v4.x.x/flow_v0.53.x-/newrelic_v4.x.x.js
  definitions/npm/newrelic_v4.x.x/flow_v0.53.x-/test_newrelic_v4.x.x.js
Labels: changes-requested, libdef, new

#2534 react-modal: Fix signature of props.onRequestClose
  definitions/npm/react-modal_v3.1.x/flow_v0.54.1-/react-modal_v3.1.x.js
  definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js
Labels: bug, changes-requested, libdef
