Repository flow-typed/flow-typed, pull requests merged in 2018-10, with the labels that each got.

#2596 fix(lodash) type for sortedUniqBy
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
  definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
Labels: enhancement, libdef, needs-updates

#2777 [smoothscroll]: Add typings for smoothscroll_v0.4.x.js
  definitions/npm/smoothscroll_v0.4.x/flow_v0.74.x-/smoothscroll_v0.4.x.js
  definitions/npm/smoothscroll_v0.4.x/test_smoothscroll_v0.4.x.js
Labels: libdef, needs-updates, new

#2750 Don't run tests for older Flows
  cli/src/commands/runTests.js
Labels: cli, on-hold

#2780 Update moment js to add defineLocale function (take 2)
  definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
  definitions/npm/moment_v2.x.x/test_moment-v2.js
Labels: enhancement, libdef, needs-updates

#2791 updated ramda types to work with 0.82
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0..x.x_partial.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_cjs_modules.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_es_modules.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_functions.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_logic.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_misc.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_object.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_relation.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0..x.x_partial.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_cjs_modules.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_es_modules.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_functions.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_logic.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_misc.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_object.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_relation.js
Labels: enhancement, libdef, question

#2819 [moment] Add all the ways to create new moment objects
  definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
  definitions/npm/moment_v2.x.x/test_moment-v2.js
Labels: enhancement, libdef, question

#2841 Add punycode v2.1.x definitions
  definitions/npm/punycode_v2.1.x/flow_v0.30.x-/punycode_v2.1.x.js
  definitions/npm/punycode_v2.1.x/test_punycode_v2.1.x.js
Labels: changes-requested, libdef, new

#2848 fix(ramda): move object `map` declaration before array ones
  definitions/npm/ramda_v0.x.x/flow_v0.25.x-v0.27.x/test_ramda_v0.21.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_list.js
Labels: changes-requested, enhancement, libdef

#2849 Update jest defs for dom testing library
  definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
  definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
Labels: question

#2854 [react-apollo] Update type for QueryRenderProps
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
  definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
Labels: enhancement, libdef
