Repository flow-typed/flow-typed, pull requests merged in 2018-03, with the labels that each got.

#1731 react-redux connect revamp
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.61.x/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.61.x/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.54.x-v0.61.x/test_connect.js
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/test_Provider.js
  definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/test_connect.js
Labels: work-in-progress

#1930 Allow CONTRIBUTING.md files in libdefs.
  cli/src/lib/libDefs.js
  cli/src/lib/npm/npmLibDefs.js
  definitions/npm/ramda_v0.x.x/CONTRIBUTING.md
Labels: enhancement

#1928 Add describe and it verbs as TDD building blocks for tests.
  CONTRIBUTING.md
  cli/src/commands/runTests.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
  definitions/tdd_framework.js
Labels: enhancement

#1935 Only mangle test file names when a name collision will occur.
  cli/src/commands/runTests.js
Labels: enhancement

#1911 Missing ramda definitions
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_functions.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
  definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_relation.js
Labels: needs-updates

#1939 Add errors to rxjs
  definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
Labels: needs-updates

#1943 Adds a list of active maintainers to README
  README.md
Labels: documentation

#1942 Removes describe and it from global scopes
  CONTRIBUTING.md
  cli/src/commands/runTests.js
  definitions/__util__/tdd_framework.js
Labels: cli-bug

#1941 Jest: type `objectContaining` and peers as if they returned their described types
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
Labels: on-hold

#1957 Replace unmaintained "unzip" with drop-in replacement "unzipper"
  cli/package.json
  cli/src/commands/runTests.js
  cli/yarn.lock
Labels: cli-bug

#1922 Support jest-enzyme version 5
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
  definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
  definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Labels: on-hold

#1690 Add firestore to firebase. Fixes gh-1657
  definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js
  definitions/npm/firebase_v4.x.x/flow_v0.34.x-/test_firebase.js
Labels: needs-updates

#1947 Fix type of Knex$Transaction.rollback
  definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js
  definitions/npm/knex_v0.13.x/test_knex-v0.13.js
Labels: needs-updates

#1962 Allow any file type in first level definition folder
  cli/src/lib/libDefs.js
  cli/src/lib/npm/__tests__/npmLibDefs-test.js
  cli/src/lib/npm/npmLibDefs.js
Labels: cli-bug

#1956 Clarify that raw React types can be used in libdefs.
  CONTRIBUTING.md
Labels: documentation

#1966 Adds changelog, starting at 2.4.0
  CHANGELOG.md
Labels: documentation

#1969 Add typing for return type of underscore's _.times
  definitions/npm/underscore_v1.x.x/flow_v0.38.x-v0.49.x/test_underscore.js
  definitions/npm/underscore_v1.x.x/flow_v0.38.x-v0.49.x/underscore_v1.x.x.js
  definitions/npm/underscore_v1.x.x/flow_v0.50.x-/test_underscore.js
  definitions/npm/underscore_v1.x.x/flow_v0.50.x-/underscore_v1.x.x.js
Labels: needs-updates

#1977 Allow a .exe extension so binaries are not deleted on windows
  cli/src/commands/runTests.js
Labels: cli-bug

#1982 Add types for Introscope v1.0.6
  definitions/npm/introscope_v1.0.10/flow_v0.52.x-/introscope_v1.0.10.js
  definitions/npm/introscope_v1.0.10/test_introscope.js
  definitions/npm/introscope_v1.0.10/test_scope.js
Labels: changes-requested

#1984 Require specifying <*> for generics
  definitions/npm/testcafe_v0.x.x/flow_v0.47.x-/testcafe_v0.x.x.js
Labels: enhancement, libdef

#1983 react-bootstrap: OverlayTrigger trigger prop takes array of triggers, not any strings
  definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js
Labels: enhancement, libdef

#1989 Look package version from package.json if not provided in package name
  cli/src/commands/__tests__/install-test.js
  cli/src/commands/install.js
Labels: cli, enhancement

#2002 fix(sequelize): correct QueryInterface.addIndex arguments
  definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
  definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
Labels: enhancement, libdef
