Repository flow-typed/flow-typed, pull requests merged in 2019-08, with the labels that each got.

#3482 [phoenix_v1.4.x] update syncState/syncDiff return value
  definitions/npm/phoenix_v1.4.x/flow_v0.104.x-/phoenix_v1.4.x.js
  definitions/npm/phoenix_v1.4.x/flow_v0.25.x-v0.103.x/phoenix_v1.4.x.js
Labels: needs-updates

#3508 [meterial-ui] Updating refs
  definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-v0.88.x/core_v1.x.x.js
Labels: work-in-progress

#3178 Add BigNumber.js 8.x.x definition file
  definitions/npm/bignumber.js_v8.x.x/flow_v0.55.x-/bignumber.js_v8.x.x.js
  definitions/npm/bignumber.js_v8.x.x/flow_v0.55.x-/test_bignumber.js_v8.x.x.js
Labels: changes-requested

#3108 Add google-protobuf definitions
  definitions/npm/google-protobuf_v3.6.x/flow_v0.83.x-/google-protobuf_v3.6.x.js
  definitions/npm/google-protobuf_v3.6.x/test_google-protobuf.js
Labels: changes-requested

#3516 Add missing properties for Subscription
  definitions/npm/rxjs_v5.0.x/flow_v0.34.x-v0.103.x/rxjs_v5.0.x.js
Labels: changes-requested

#3526 [@testing-library/react_v8.x.x] Add act function
  definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
  definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/test_react_v8.x.x.js
  definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/react_v8.x.x.js
  definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/test_react_v8.x.x.js
Labels: changes-requested

#3523 Add type definitions for @apollo/react-hooks package
  definitions/npm/@apollo/react-hooks_v3.x.x/CONTRIBUTING.md
  definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
  definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/test_react-hooks_v3.x.x.js
  definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js
  definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/test_react-hooks_v3.x.x.js
Labels: changes-requested
